# Autogenerated wrapper script for LicenseSpring_jll for i686-w64-mingw32
export liblicensespring

using LibCURL_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("LicenseSpring")
JLLWrappers.@declare_library_product(liblicensespring, "LicenseSpring.dll")
function __init__()
    JLLWrappers.@generate_init_header(LibCURL_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        liblicensespring,
        "bin\\LicenseSpring.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
